# Generated by Django 5.0.2 on 2024-05-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0004_remove_house_price_room_price_room_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentalapp.owner'),
        ),
    ]
