# Generated by Django 5.0.2 on 2024-05-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0005_house_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='cover_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
