# Generated by Django 4.2.3 on 2024-05-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0007_owner_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='profile_pic',
            field=models.ImageField(default='files/owners/a.png', upload_to='media/owners/'),
        ),
    ]
