# Generated by Django 4.2.3 on 2024-05-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0008_alter_owner_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='profile_pic',
            field=models.ImageField(default='owners/a.png', upload_to='owners/'),
        ),
    ]
