# Generated by Django 4.2.3 on 2024-05-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0009_alter_owner_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='cover_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
