# Generated by Django 5.0.2 on 2024-05-27 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0011_rename_rooom_tenancy_room_alter_house_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentalapp.tenant'),
        ),
    ]
