# Generated by Django 5.0.2 on 2024-05-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0012_room_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='no_floors',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
