# Generated by Django 5.0.2 on 2024-05-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0013_house_no_floors_room_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(default='ground', max_length=50),
        ),
    ]
