# Generated by Django 5.0.2 on 2024-06-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0016_alter_tenant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenancy',
            name='house',
        ),
    ]
