# Generated by Django 5.0.2 on 2024-06-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0017_remove_room_tenant_remove_tenancy_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='last_charged',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
