# Generated by Django 5.0.2 on 2024-06-16 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0018_tenancy_last_charged'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='arrears',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('amount_paid', models.IntegerField(default=0)),
                ('cleared', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=254)),
                ('start_date', models.DateField()),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.tenancy')),
            ],
        ),
    ]
