# Generated by Django 5.0.2 on 2024-06-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0019_tenancy_arrears_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='last_charged',
            field=models.DateField(null=True),
        ),
    ]
