# Generated by Django 5.0.2 on 2024-06-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0020_alter_tenancy_last_charged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('tenancy', models.ForeignKey(null='True', on_delete=django.db.models.deletion.SET_NULL, to='rentalapp.tenancy')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('rent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentalapp.rent')),
            ],
        ),
    ]
